function results = compile_tomoBEAR(build_destination)
build = false;
if nargin == 0
    build_destination = "cryo_et_pipeline";
    results = [];
end
if build == true
    if ~verLessThan("matlab", "9.9") % R2020b
        opts = compiler.build.StandaloneApplicationOptions("pipeline/runPipeline.m");
        opts.ExecutableName = "run_cryo_et_pipeline";
        opts.CustomHelpTextFile = "README";
        opts.ExecutableVersion = "0.0.0.1";
        opts.AutoDetectDataFiles = false;
        dynamo_files = getDynamoFiles("dynamo");
        opts.AdditionalFiles = [...
            "modules/BatchRunTomo.m",...
            ...%"./modules/BinarizeStacks.m",...
            "modules/BinStacks.m",...
            "modules/CreateStacks.m",...
            "modules/DynamoTiltSeriesAlignment.m",...
            "modules/DynamoTemplateMatching.m",...
            "modules/DynamoCleanStacks.m",...
            "modules/DynamoTemplateMatching.m",...
            "modules/EMDTemplateGeneration.m",...
            "modules/TemplateGenerationFromFile.m",...
            "modules/GainCorrection.m",...
            "modules/GCTFCtfphaseflipCTFCorrection.m",...
            "modules/MetaData.m",...
            "modules/Module.m",...
            "modules/MotionCor2.m",...
            "modules/Reconstruct.m",...
            "modules/SortFiles.m",...
            "modules/SUSAN.m",...
            "modules/TemplateMatchingPostProcessing.m",...
            "modules/TomoAlign.m",...
            "configuration/ConfigurationParser.m",...
            "environment/concatAndAddPathsRecursive.m",...
            "environment/initializeEnvironment.m",...
            "json/JSON.m",...
            "pipeline/Pipeline.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ParticlesInfo/ParticlesInfo.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ParticlesInfo/private/ParticlesInfo_calc_min_distance.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ParticlesInfo/private/ParticlesInfo_defocus_per_ptcl.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ParticlesInfo/private/ParticlesInfo_discard_min_distance.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ParticlesInfo/private/ParticlesInfo_euZXZ_2_euZYZ.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ParticlesInfo/private/ParticlesInfo_euZYZ_2_euZXZ.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ParticlesInfo/private/ParticlesInfo_load_by_blocks.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ParticlesInfo/private/ParticlesInfo_save_by_blocks.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ParticlesInfo/private/ParticlesInfo_select_by_tilt_angle.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ParticlesInfo/private/ParticlesInfo_shift_rot.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@ReferenceInfo/ReferenceInfo.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Data/@TomosInfo/TomosInfo.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+IO/read_mrc.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Modules/@Aligner/Aligner.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Modules/@Aligner/private/Aligner_list_cone_search.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Modules/@Aligner/private/Aligner_list_inplane_search.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Modules/@Aligner/private/Aligner_list_points_cylinder.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Modules/@Aligner/private/Aligner_list_points_ellipsoid.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Modules/@Averager/Averager.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Modules/@CtfEstimator/CtfEstimator.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Project/@Manager/Manager.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Utils/RawRW.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Utils/TxtRW.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Utils/exist_file.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Utils/fsc_get.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Utils/get_mrc_info.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Utils/is_extension.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Utils/mask_sphere.m",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Utils/private/fsc_get_core.mexa64",...
            "/home/risanche/Projects/SUSAN/alpha/+SUSAN/+Utils/private/mask_sphere_core.mexa64",...
            dynamo_files(:)'
            ];
        
        opts.TreatInputsAsNumeric = false;
        opts.Verbose = true;
        opts.OutputDir = build_destination;
        results = compiler.build.standaloneApplication(opts);
    else
        error("ERROR: not supported in this version of MATLAB, R2020b needed, please run the application compiler app!")
    end
end
system("./change_permissions_for_build.sh");
fid = fopen("tomoBEAR/for_redistribution_files_only/run_tomoBEAR.sh", "r+");
counter = 1;
while ~feof(fid)
    text_line{counter} = string(fgets(fid));
    if contains(text_line{counter}, "LD_LIBRARY_PATH=.:${MCRROOT}/runtime/glnxa64 ;")
        text_line{counter} = strrep(text_line{counter}, "LD_LIBRARY_PATH=.:${MCRROOT}/runtime/glnxa64 ;",...
            "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:.:${MCRROOT}/runtime/glnxa64 ;");
    end
    counter = counter + 1;
end

fseek(fid, 0, "bof");
for i = 1:counter-1
    fprintf(fid, "%s", text_line{i});
end
fclose(fid);
end