function file_paths = getFilePathsFromLastBatchruntomoRun(configuration, file_extension)
batchruntomo_folders = dir(configuration.processing_path + string(filesep)...
    + configuration.output_folder + string(filesep) + "*_BatchRunTomo_*");
if length(batchruntomo_folders) >= 1
    order = sortDirOutputByPipelineStepNumbering(batchruntomo_folders, configuration);
    field_names = fieldnames(configuration.tomograms);
    if extractBetween(file_extension, 1, 1) == "_"
        file_paths{1} = batchruntomo_folders(order(1)).folder + string(filesep)...
            + batchruntomo_folders(order(1)).name + string(filesep)...
            + field_names{configuration.set_up.j} + string(filesep)...
            + field_names{configuration.set_up.j} + string(file_extension);
    else
        file_paths{1} = batchruntomo_folders(order(1)).folder + string(filesep)...
            + batchruntomo_folders(order(1)).name + string(filesep)...
            + field_names{configuration.set_up.j} + string(filesep)...
            + field_names{configuration.set_up.j} + "." + string(file_extension);
    end
else
    file_paths = {};
end
end

