function file_paths = getFilePathsFromLastBatchruntomoRun(configuration, file_extension)
batchruntomo_folders = dir(configuration.processing_path + string(filesep)...
    + configuration.output_folder + string(filesep) + "*_BatchRunTomo_*");
order = sortDirOutputByPipelineStepNumbering(batchruntomo_folders, configuration);
field_names = fieldnames(configuration.tomograms);
file_paths{1} = batchruntomo_folders(order(1)).folder + string(filesep)...
    + batchruntomo_folders(order(1)).name + string(filesep)...
    + field_names{configuration.set_up.j} + string(filesep)...
    + field_names{configuration.set_up.j} + "." + string(file_extension);
end

