name: Issue Report
description: File a bug or any other general issue
title: "[ISSUE]: "
labels: ["pending"]
body:
  - type: input
    id: tomobear-ver
    attributes:
      label: TomoBEAR version
      description: Which version of TomoBEAR package do you use? If you cloned specific branch or commit, please execute "git log --pretty="%H - %cd" -n 1" in your cloned TomoBEAR source code folder and put its output in this field
      placeholder: v0.4.0
    validations:
      required: true
  - type: dropdown
    id: tomobear-form
    attributes:
      label: TomoBEAR distribution form
      description: Which kind of TomoBEAR distribution form do you use?
      multiple: true
      options:
        - Full (interactive) MATLAB
        - Standalone
    validations:
      required: true
  - type: dropdown
    id: computing-system
    attributes:
      label: Computing system
      description: Which kind of computing system do you use?
      multiple: true
      options:
        - Standalone GPU workstation
        - HPC cluster (interactive computing node)
        - HPC cluster (via scheduler submission)
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Issue description
      description: Provide a clear description of what happend and what did you expect to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: configs
    attributes:
      label: Input configuration (JSON) file
      description: Please copy and paste your input configuration (JSON) file. Use 
      value: "```JSON { ... } ```"
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Add any other context about the problem here (actions to reproduce, log/error messages, example data, additional configurations, screenshots, links/references).
  - type: input
    id: gpu-info
    attributes:
      label: GPU setup 
      description: If the problem might be related to the GPUs, please describe your GPU setup (amount/type/memory) and CUDA version(s) 
      placeholder: 4 x NVIDIA Ampere A40-48GB; CUDA-11.5
  - type: textarea
    id: software-info
    attributes:
      label: Software setup 
      description: Give here list of software and their versions (and other relevant info) which may be related to the issue (e.g. MATLAB, IMOD, Dynamo, MotionCor2, AreTomo, Gctf, IsoNet, etc.)   
      placeholder: MATLAB-2021a, IMOD-4.11.24; Gctf-v1.18; etc.
